const CHANGE_FOOTER_TAP = 'CHANGE_FOOTER_TAP' // 切换底部按钮状态
const CHANGE_SEARCH_BAR_SHOW = 'CHANGE_SEARCH_BAR_SHOW' // 显示搜索栏
const CHANGE_FOOTER_NAV_SHOW = 'CHANGE_FOOTER_NAV_SHOW' // 显示底部导航栏
const CHANGE_DETAILS_NAV_SHOW = 'CHANGE_DETAILS_NAV_SHOW' // 详细页面的顶栏显示属性
const CHANGE_DETAILS_NAV_TITLE = 'CHANGE_DETAILS_NAV_TITLE' // 详细页面的顶栏标题
const CHANGE_MARK_SHOW = 'CHANGE_MARK_SHOW' // 城市定位的标签图标

export default {
  CHANGE_FOOTER_TAP,
  CHANGE_SEARCH_BAR_SHOW,
  CHANGE_FOOTER_NAV_SHOW,
  CHANGE_DETAILS_NAV_SHOW,
  CHANGE_DETAILS_NAV_TITLE,
  CHANGE_MARK_SHOW
}
